version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livrili
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    image: sfarahmedkhalil/livrili:1.2
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/livrili
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      JWT_SECRET: qrtKisXDK5Zhr0wSxiA4BN2RElr3qTndF3GOzQhchNA
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

    depends_on:
      - mysql

volumes:
  mysql_data:
